// <auto-generated />
using System;
using MVC_OnlineKursApp_ProjesiCozumu.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_OnlineKursApp_ProjesiCozumu.Migrations
{
    [DbContext(typeof(OnlineKursDbContext))]
    partial class OnlineKursDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgitimEgitmen", b =>
                {
                    b.Property<Guid>("EgitimlerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EgitmenlerID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EgitimlerID", "EgitmenlerID");

                    b.HasIndex("EgitmenlerID");

                    b.ToTable("EgitimEgitmen");
                });

            modelBuilder.Entity("EgitimOgrenci", b =>
                {
                    b.Property<Guid>("EgitimlerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OgrencilerID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EgitimlerID", "OgrencilerID");

                    b.HasIndex("OgrencilerID");

                    b.ToTable("EgitimOgrenci");
                });

            modelBuilder.Entity("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Egitim", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SeansId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("ToplamSaat")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("SeansId");

                    b.HasIndex("UrunId");

                    b.ToTable("Egitimler");
                });

            modelBuilder.Entity("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Egitmen", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IseBaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IsiBirakmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Egitmenler");
                });

            modelBuilder.Entity("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Ogrenci", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Seans", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<string>("BaslangicSaati")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BitisSaati")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EgitimGunleri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Seanslar");
                });

            modelBuilder.Entity("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Teknoloji", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Teknolojiler");
                });

            modelBuilder.Entity("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Urun", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Saat")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TeknolojiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ZorlukSeviyesi")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.HasIndex("TeknolojiId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("EgitimEgitmen", b =>
                {
                    b.HasOne("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Egitim", null)
                        .WithMany()
                        .HasForeignKey("EgitimlerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Egitmen", null)
                        .WithMany()
                        .HasForeignKey("EgitmenlerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EgitimOgrenci", b =>
                {
                    b.HasOne("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Egitim", null)
                        .WithMany()
                        .HasForeignKey("EgitimlerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Ogrenci", null)
                        .WithMany()
                        .HasForeignKey("OgrencilerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Egitim", b =>
                {
                    b.HasOne("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Seans", "Seans")
                        .WithMany("SeansEgitimleri")
                        .HasForeignKey("SeansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Urun", "Urun")
                        .WithMany("Egitimler")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seans");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Urun", b =>
                {
                    b.HasOne("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Teknoloji", "teknoloji")
                        .WithMany("Urunler")
                        .HasForeignKey("TeknolojiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("teknoloji");
                });

            modelBuilder.Entity("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Seans", b =>
                {
                    b.Navigation("SeansEgitimleri");
                });

            modelBuilder.Entity("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Teknoloji", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("MVC_OnlineKursApp_ProjesiCozumu.Models.Entities.Concrate.Urun", b =>
                {
                    b.Navigation("Egitimler");
                });
#pragma warning restore 612, 618
        }
    }
}
